### ISSUE TITLE
Article Name

### ISSUE THREAD

**Issue by amirabas-kz** [Blarc/qrs-detection#1]
What is the corresponding article? H.C Chen and S.W Chen have published several papers about this topic.

**Comment by Blarc** [comment]
You can find it in the [report.pdf](https://github.com/Blarc/qrs-detection/blob/main/report.pdf) under literature section:
```
H. C. Chen and S. W. Chen, "A moving average based filtering system with its application to real-time QRS detection"
Computers in Cardiology, 2003, 2003, pp. 585-588, doi: 10.1109/CIC.2003.1291223.
```
